# Generated by Django 5.2.4 on 2025-07-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='Без коментаря'),
            preserve_default=False,
        ),
    ]
